# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: exlib-status-api

provider:
  name: aws
  runtime: python3.8
  region: ${file(auth.json):region_name}
  stage: prod
  environment:
    access_key: ${file(auth.json):aws_access_key_id}
    secret_access: ${file(auth.json):aws_secret_access_key}
    region_name: ${file(auth.json):region_name}
    main_table: ${file(auth.json):main_table}
    emergency_table: ${file(auth.json):emergency_table}
    outage_table: ${file(auth.json):outage_table}
    local_timezone: ${file(auth.json):local_timezone}
    slack_scott: ${file(auth.json):slack_scott}
    slack_dis_dev: ${file(auth.json):slack_dis_dev}
    exl_user: ${file(auth.json):exl_user}
    exl_pass: ${file(auth.json):exl_pass}
    exl_system_id: ${file(auth.json):exl_system_id}

package:

  exclude:
    - .serverless/**
    - node_modules/**
    - img/**
    - README.md
    - .git/**
    - .gitignore
    - auth-example.json
    - dynamo_starter.json

functions:
  dynamo_updater:
    handler: dynamo_updater.handler
    events:
      - schedule: rate(6 minutes)
  outage-checker:
    handler: outage-checker.handler
    events:
      - schedule: rate(6 minutes)
  webAPI:
    handler: webAPI.handler
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
